[toolchain]
anchor_version = "0.30.0" # `anchor-cli` version to use
solana_version = "1.18.13" # Solana version to use

[features]
seeds = false
skip-lint = false
idl-build = ["anchor-lang/idl-build"]

[programs.localnet]
oridion = "33J2bC6ZYvg8Y77MWULZEWpWRkxCoM2aziZ5f67dwBXi"

[programs.devnet]
oridion = "6ihF5TkmwWKPJfxDWJoA6f6EuLYqvPKdMbj9ohJ6n7kg" #Oridion dev wallet

[programs.mainnet]
oridion = "33J2bC6ZYvg8Y77MWULZEWpWRkxCoM2aziZ5f67dwBXi"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://mainnet.helius-rpc.com/?api-key=e9be3c89-9113-4c5d-be19-4dfc99d8c8f4"
#cluster = "mainnet"
#cluster = "devnet"
#cluster = "localnet"

wallet = ""

[scripts]
