[toolchain]
anchor_version = "0.29.0" # `anchor-cli` version to use
solana_version = "1.17.0" # Solana version to use

[features]
seeds = false
skip-lint = false

[programs.localnet]
oridion = ""

[programs.devnet]
ord_prog_dev = "" #Oridion dev wallet

[programs.mainnet]
ord_prog_main = "" #Oridion mainnet wallet

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = ""

[scripts]

#this may not be needed. Isn't in the full on anchor project.
[test.validator]
bind_address = "127.0.0.1"
